server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
spring:
  application:
    name: gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    region: default
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
zuul:
  routes:
    task-service:
      path: /taskservice/**
      serviceId: task-service
    notification-service:
      path: /notificationservice/**
      serviceId: notification-service
hystrix:
  command:
    task-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000