server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info, refresh
      path-mapping:
        health: healthcheck
spring:
  application:
    name: notification-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notifications_database
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka