server:
  port: 8761
spring:
  application:
    name: registry-service
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
eureka:
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
    responseCacheUpdateIntervalMs: 5000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka