server:
  port: 0
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info, refresh
      path-mapping:
        health: healthcheck
      base-path: /
spring:
  application:
    name: task-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tasks_database
eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
    registryFetchIntervalSeconds: 5
hystrix:
  threadpool:
    getData:
      core: 20
      allowMaximumSizeToDivergeFromCoreSize: true
      maximumSize: 100
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5001
ribbon:
  eureka:
    enabled: true
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 3
  ConnectTimeout: 2501
  ReadTimeout: 2501